name: Ci

on:
  push:
    branches:
    - main
  pull_request:
  release:
    types: [created]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        sudo apt update
        sudo -EDEBIAN_FRONTEND apt install -y --no-install-recommends wabt
      env:
        DEBIAN_FRONTEND: noninteractive
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x
    - run: |
        npm install
        make test

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    needs:
    - tests
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        registry-url: 'https://registry.npmjs.org'
    - run: make
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
